### ISSUE TITLE
TODO List / Feature Requests

### ISSUE THREAD

**Issue by molarmanful** [molarmanful/DASH#1]
# TODO:

**Immediate**:
- [x] Infinite lists? (maybe via generators)
- [x] Some sort of regex support
- [x] Package manager / libraries
- [x] Non-base-10 number systems (minimum binary, octal, and hexadecimal)
- [x] Object/hash datatype
- [ ] Custom regex flavors/additions
- [ ] Escape codes for strings
- [ ] Test cases

**Ongoing**:
- Error handling / debugging
- Interpreter optimization
- Predefined variables
- More string / array / I/O functions
- Syntactic sugar
